COMMANDS = [
"Click on the orange square.",
"Click on the pink square.",
"Click on the orange square.",
"Click on the red wide rectangle.",
"Click on the orange square.",
"Click on the red square.",
"Click on the pink square.",
"Click on the red square.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue square.",
"Click on the red wide rectangle.",
"Click on the orange square.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the red square.",
"Click on the orange square.",
"Click on the red wide rectangle.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue square.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the red wide rectangle.",
"Click on the yellow square.",
"Click on the red wide rectangle.",
"Click on the red square.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the blue square.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the red square.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the red square.",
"Click on the blue square.",
"Click on the orange square.",
"Click on the pink wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the blue square.",
"Click on the pink wide rectangle.",
"Click on the green square.",
"Click on the yellow wide rectangle.",
"Click on the orange square.",
"Click on the yellow square.",
"Click on the red square.",
"Click on the green square.",
"Click on the red square.",
"Click on the blue square.",
"Click on the red wide rectangle.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the red square.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the orange square.",
"Click on the orange wide rectangle.",
"Click on the blue square.",
"Click on the red square.",
"Click on the green square.",
"Click on the red square.",
"Click on the red wide rectangle.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the orange square.",
"Click on the yellow square.",
"Click on the orange wide rectangle.",
"Click on the pink square.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the green square.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the pink square.",
"Click on the green square.",
"Click on the blue square.",
"Click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the red square.",
"Click on the green square.",
"Click on the pink square.",
"Click on the yellow square.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the blue square.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the yellow square.",
"Click on the pink square.",
"Click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow square.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange square.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange square.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the green wide rectangle.",
"Click on the yellow square.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the blue wide rectangle.",
"Click on the green square.",
"Click on the pink square.",
"Click on the red square.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the yellow square.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow square.",
"Click on the red square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange square.",
"Click on the red square.",
"Click on the green wide rectangle.",
"Click on the blue square.",
"Click on the red square.",
"Click on the orange square.",
"Click on the blue square.",
"Click on the green wide rectangle.",
"Click on the red square.",
"Click on the green square.",
"Click on the red square.",
"Click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green square.",
"Click on the yellow wide rectangle.",
"Click on the orange square.",
"Click on the orange wide rectangle.",
"Click on the green square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the orange square.",
"Click on the red wide rectangle.",
"Click on the pink square.",
"Click on the orange wide rectangle.",
"Click on the yellow square.",
"Click on the orange wide rectangle.",
"Click on the green square.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the green wide rectangle.",
"Click on the green square.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the orange square.",
"Click on the red square.",
"Click on the green wide rectangle.",
"Click on the red square.",
"Click on the blue square.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the red square.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the blue square.",
"Click on the green wide rectangle.",
"Click on the red square.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the green square.",
"Click on the red square.",
"Click on the green wide rectangle.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the red square.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the green square.",
"Click on the orange square.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange square.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange square.",
"Click on the red wide rectangle.",
"Click on the pink square.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the green square.",
"Click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the pink wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the blue square.",
"Click on the red square.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the red square.",
"Click on the blue wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the red square.",
"Click on the orange square.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the green wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the yellow square.",
"Click on the red square.",
"Click on the blue square.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the orange square.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the green wide rectangle.",
"Click on the pink square.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Click on the pink square.",
"Click on the red square.",
"Click on the green square.",
"Click on the blue square.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the green square.",
"Click on the red wide rectangle.",
"Click on the red square.",
"Click on the red wide rectangle.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the red square.",
"Click on the blue square.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red square.",
"Click on the red wide rectangle.",
"Click on the red square.",
"Click on the orange wide rectangle.",
"Click on the pink square.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle.",
"Click on the orange square.",
"Click on the orange wide rectangle.",
"Click on the yellow square.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the blue wide rectangle.",
"Click on the yellow square.",
"Click on the green square.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the orange square.",
"Click on the green square.",
"Click on the orange square.",
"Click on the blue square.",
"Click on the red square.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the green square.",
"Click on the blue square.",
"Click on the red square.",
"Click on the pink square.",
"Click on the blue wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green square.",
"Click on the yellow wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange square.",
"Click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the green square.",
"Click on the red square.",
"Click on the blue square.",
"Click on the blue wide rectangle.",
"Click on the green square.",
"Click on the orange wide rectangle.",
"Click on the green square.",
"Click on the red wide rectangle.",
"Click on the green square.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green wide rectangle.",
"Click on the green square.",
"Click on the blue square.",
"Click on the green square.",
"Click on the orange wide rectangle.",
"Click on the yellow square.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the orange square.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the blue square.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the pink square.",
"Click on the orange square.",
"Click on the yellow square.",
"Click on the orange wide rectangle.",
"Click on the orange square.",
"Click on the yellow wide rectangle.",
"Click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the pink square.",
"Click on the green square.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the orange square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the green square.",
"Click on the orange wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the blue square.",
"Click on the pink wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the green wide rectangle.",
"Click on the blue square.",
"Click on the blue wide rectangle.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the orange square.",
"Click on the orange wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the red square.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue square.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the blue square.",
"Click on the yellow wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the yellow square.",
"Click on the green square.",
"Click on the blue wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the blue square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the yellow square.",
"Click on the orange square.",
"Click on the green wide rectangle.",
"Click on the blue square.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the yellow square.",
"Click on the red square.",
"Click on the pink wide rectangle.",
"Click on the blue square.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the green square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the orange square.",
"Click on the green square.",
"Click on the blue square.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the pink wide rectangle.",
"Click on the blue square.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the orange square.",
"Click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the green square.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the green square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue square.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the orange square.",
"Click on the green square.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange square.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the red square.",
"Click on the pink square.",
"Click on the blue square.",
"Click on the red wide rectangle.",
"Click on the yellow square.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the yellow wide rectangle.",
"Click on the red square.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the yellow square.",
"Click on the blue square.",
"Click on the orange square.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the orange square.",
"Click on the green square.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the orange square.",
"Click on the pink square.",
"Click on the blue wide rectangle.",
"Click on the yellow square.",
"Click on the green square.",
"Click on the green wide rectangle.",
"Click on the pink square.",
"Click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the pink square.",
"Click on the yellow square.",
"Click on the orange square.",
"Click on the pink square.",
"Click on the green square.",
"Click on the blue square.",
"Click on the yellow square.",
"Click on the blue square.",
"Click on the red wide rectangle.",
"Click on the red square.",
"Click on the yellow square.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the pink square.",
"Click on the red square.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange square.",
"Click on the blue square.",
"Click on the red square.",
"Click on the blue wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green square.",
"Click on the red square.",
"Click on the red wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the green square.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the pink wide rectangle.",
"Click on the red square.",
"Click on the green square.",
"Click on the blue wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the pink square.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the yellow square.",
"Click on the red wide rectangle.",
"Click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the blue square.",
"Click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow square.",
"Click on the pink wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the blue square.",
"Click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green wide rectangle.",
"Click on the yellow square.",
"Click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the pink square.",
"Click on the green square.",
"Click on the blue square.",
"Click on the yellow wide rectangle.",
"Click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the green square.",
"Click on the pink wide rectangle.",
"Click on the green square.",
"Click on the blue wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the yellow square and then click on the blue wide rectangle.",
"Click on the yellow wide rectangle and then click on the yellow square.",
"Click on the orange wide rectangle.",
"Click on the yellow square.",
"Click on the blue square and then click on the red square.",
"Click on the orange square and then click on the blue square.",
"Click on the blue square and then click on the green wide rectangle.",
"Click on the green wide rectangle.",
"Click on the blue wide rectangle and then click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the pink wide rectangle and then click on the yellow wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow square and then click on the green wide rectangle.",
"Click on the yellow square.",
"Click on the orange wide rectangle.",
"Click on the orange square and then click on the red wide rectangle.",
"Click on the orange square.",
"Click on the red wide rectangle and then click on the orange square.",
"Click on the yellow wide rectangle.",
"Click on the orange square.",
"Click on the orange wide rectangle and then click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the red square.",
"Click on the red square and then click on the orange square.",
"Click on the yellow square and then click on the blue wide rectangle.",
"Click on the red square.",
"Click on the blue square.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the blue square and then click on the red square.",
"Click on the pink square and then click on the green wide rectangle.",
"Click on the yellow square and then click on the orange square.",
"Click on the orange wide rectangle and then click on the blue square.",
"Click on the green square.",
"Click on the yellow square.",
"Click on the blue wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the pink wide rectangle and then click on the pink square.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle and then click on the blue square.",
"Click on the pink square.",
"Click on the yellow square.",
"Click on the orange square and then click on the pink square.",
"Click on the yellow square.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the green square and then click on the pink wide rectangle.",
"Click on the yellow wide rectangle and then click on the red wide rectangle.",
"Click on the yellow wide rectangle and then click on the blue wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the blue square and then click on the orange square.",
"Click on the pink wide rectangle and then click on the blue square.",
"Click on the pink wide rectangle and then click on the red square.",
"Click on the pink wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue square.",
"Click on the red square.",
"Click on the red wide rectangle and then click on the green wide rectangle.",
"Click on the blue square and then click on the yellow wide rectangle.",
"Click on the pink square and then click on the orange square.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the green square and then click on the green wide rectangle.",
"Click on the orange wide rectangle and then click on the yellow square.",
"Click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the blue square and then click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle and then click on the pink wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the red square.",
"Click on the blue square and then click on the yellow wide rectangle.",
"Click on the green wide rectangle and then click on the yellow square.",
"Click on the blue wide rectangle.",
"Click on the pink wide rectangle and then click on the blue square.",
"Click on the orange wide rectangle.",
"Click on the yellow square and then click on the orange square.",
"Click on the green wide rectangle.",
"Click on the yellow square.",
"Click on the pink square and then click on the green square.",
"Click on the orange wide rectangle.",
"Click on the red square.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle and then click on the green wide rectangle.",
"Click on the red wide rectangle.",
"Click on the yellow wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the orange wide rectangle and then click on the yellow wide rectangle.",
"Click on the red wide rectangle.",
"Click on the orange square and then click on the pink square.",
"Click on the yellow square and then click on the green wide rectangle.",
"Click on the red wide rectangle and then click on the pink square.",
"Click on the green wide rectangle.",
"Click on the red wide rectangle and then click on the orange wide rectangle.",
"Click on the red wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the red square and then click on the blue wide rectangle.",
"Click on the blue square.",
"Click on the red square and then click on the pink wide rectangle.",
"Click on the green square and then click on the yellow square.",
"Click on the green square.",
"Click on the green wide rectangle and then click on the orange square.",
"Click on the red wide rectangle.",
"Click on the pink square and then click on the green square.",
"Click on the orange square and then click on the red square.",
"Click on the red square.",
"Click on the blue wide rectangle and then click on the yellow wide rectangle.",
"Click on the blue square.",
"Click on the pink wide rectangle and then click on the blue square.",
"Click on the green square and then click on the yellow wide rectangle.",
"Click on the blue wide rectangle and then click on the yellow wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the green square.",
"Click on the green square and then click on the yellow square.",
"Click on the green wide rectangle and then click on the orange wide rectangle.",
"Click on the green square.",
"Click on the pink square.",
"Click on the yellow square and then click on the blue square.",
"Click on the orange square and then click on the orange wide rectangle.",
"Click on the blue square.",
"Click on the red square and then click on the green square.",
"Click on the yellow wide rectangle and then click on the blue square.",
"Click on the yellow wide rectangle and then click on the green square.",
"Click on the pink wide rectangle and then click on the blue wide rectangle.",
"Click on the blue square.",
"Click on the blue square and then click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the red square and then click on the orange wide rectangle.",
"Click on the red square.",
"Click on the pink square.",
"Click on the orange wide rectangle and then click on the red square.",
"Click on the green wide rectangle and then click on the yellow square.",
"Click on the red wide rectangle and then click on the yellow wide rectangle.",
"Click on the green wide rectangle.",
"Click on the yellow wide rectangle and then click on the blue square.",
"Click on the pink square.",
"Click on the red square and then click on the orange square.",
"Click on the red square.",
"Click on the yellow square.",
"Click on the orange wide rectangle and then click on the orange square.",
"Click on the yellow square.",
"Click on the pink square.",
"Click on the red wide rectangle.",
"Click on the red square.",
"Click on the red square and then click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the pink square and then click on the pink wide rectangle.",
"Click on the blue wide rectangle and then click on the green wide rectangle.",
"Click on the pink wide rectangle.",
"Click on the yellow square.",
"Click on the orange square and then click on the orange wide rectangle.",
"Click on the blue wide rectangle and then click on the green square.",
"Click on the red wide rectangle.",
"Click on the green wide rectangle and then click on the green square.",
"Click on the pink square.",
"Click on the yellow square and then click on the blue wide rectangle.",
"Click on the yellow wide rectangle and then click on the green square.",
"Click on the yellow square and then click on the yellow wide rectangle.",
"Click on the orange wide rectangle.",
"Click on the blue wide rectangle and then click on the yellow wide rectangle.",
"Click on the blue square and then click on the red square.",
"Click on the orange square.",
"Click on the red wide rectangle.",
"Click on the blue wide rectangle.",
"Click on the green wide rectangle and then click on the orange square.",
"Click on the pink wide rectangle.",
"Click on the orange wide rectangle and then click on the blue wide rectangle.",
"Click on the blue wide rectangle and then click on the blue square.",
"Click on the orange wide rectangle and then click on the yellow square.",
"Click on the green wide rectangle.",
"Click on the yellow square.",
"Click on the blue wide rectangle and then click on the orange square.",
"Click on the yellow wide rectangle and then click on the green square.",
"Click on the pink wide rectangle.",
"Click on the red wide rectangle.",
"Click on the green square and then click on the red square.",
"Click on the yellow wide rectangle.",
"Click on the green square and then click on the blue wide rectangle.",
"Click on the pink square and then click on the blue square.",
"Click on the orange square.",
"Click on the blue wide rectangle.",
"Click on the pink square and then click on the red square.",
"Click on the blue square.",
"Click on the red wide rectangle.",
"Click on the orange square.",
"Click on the blue square.",
"Click on the pink square.",
]
